"""Template residue — unfilled conference/journal template boilerplate (ACM
sample defaults, placeholder ISBN/DOI, default dates/location, draft watermark).

axis = AUTHORSHIP, output = FLAG, severity = LOW, distribution = OPEN.

Per design: this is a FORMATTING signal at most. It indicates an unfinalized /
hastily prepared draft, NOT fraud, and it lands on the format meter only — it
can never raise the integrity (造假) index.
"""
from __future__ import annotations

import re
from typing import List

from ..types import Axis, Evidence, Finding, OutputType, Severity

# (pattern, label) — all LOW severity, authorship axis
_PATTERNS = [
    (r"make sure to enter the correct conference title", "ACM rights-confirmation instruction left in"),
    (r"do not use this code|generate the correct terms for your paper", "ACM CCS-concepts placeholder left in"),
    (r"proof of the zonklar equations", "IEEEtran sample appendix placeholder left in"),
    (r"this should be a simple paragraph before the references", "IEEEtran acknowledgments placeholder left in"),
    (r"a sample article using ieeetran", "IEEEtran sample title left in"),
    (r"you can use a bibliography generated by bibtex", "IEEEtran references placeholder left in"),
    (r"if you (?:include|will not include) a photo|ieeebiographynophoto", "IEEEtran biography placeholder left in"),
    (r"if you have a single appendix", "IEEEtran appendix instruction left in"),
    (r"manuscript received april 19, 2021", "IEEEtran sample manuscript date left in"),
    (r"978-1-4503-x{4}", "placeholder ISBN"),
    (r"978-x-x{4}", "placeholder ISBN (fully unfilled)"),
    (r"/yyyy/mm", "placeholder ISBN year/month"),
    (r"x{6,}\.x{6,}", "placeholder DOI"),
    (r"conference acronym\s*['’\u2019]?\s*xx", "placeholder conference name"),
    (r"unpublished working draft\.?\s*not for distribution", "draft watermark not removed"),
    (r"woodstock,?\s*ny", "template default location"),
    (r"revised \d{1,2} \w+ 200\d.*?accepted \d{1,2} \w+ 200\d", "template default received/accepted dates"),
    (r"\[n\.\s*d\.\]", "missing-date placeholder in references"),
]
_COMPILED = [(re.compile(p, re.IGNORECASE | re.DOTALL), label) for p, label in _PATTERNS]


def run(text: str) -> List[Finding]:
    findings: List[Finding] = []
    seen = set()
    for rx, label in _COMPILED:
        m = rx.search(text)
        if not m or label in seen:
            continue
        seen.add(label)
        snippet = re.sub(r"\s+", " ", m.group(0))[:80]
        findings.append(
            Finding(
                detector="template_residue",
                axis=Axis.AUTHORSHIP,
                output_type=OutputType.FLAG,
                severity=Severity.LOW,
                message=f"{label} (formatting/template residue — NOT a fraud signal): {snippet!r}",
                evidence=Evidence(claim="unfinalized template boilerplate", reported=snippet),
            )
        )
    return findings
